### ISSUE TITLE
В классе GameStore метод containsGame не видит игру, добавленную через publishGame

### ISSUE THREAD

**Issue by IraDol** [IraDol/team-project-origin#1]
# Описание
В классе GameStore метод containsGame возвращает false после добавления игры через publishGame

# Локация дефекта
https://github.com/IraDol/team-project-origin/blob/fe259677edc28d45041cb8deaae1fbffb5f47a3b/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения
1. Открыть  [класс GameStoreTest](https://github.com/IraDol/team-project-origin/blob/main/src/test/java/ru/netology/GameStoreTest.java#L8) в IDEA
2. Запустить тест shouldAddGame
3. Посмотреть результат теста в консоли

*Ожидаемый результат* - true, добавленная игра в каталоге
*Фактический результат* - false, метод containsGame не видит добавленную игру

# Скриншот
<img width="984" alt="image" src="https://user-images.githubusercontent.com/97681517/178336557-abf7e68b-7d6f-4c11-a797-e8a88d47d1dd.png">

# Окружение

* **Операционная система** macOS Big Sur
* **IDE** IntelliJ IDEA Community Edition 2022.1
* **Java** OpenJDK 11

**Comment by Natasssha** [comment]
Done
