### ISSUE TITLE
В классе GameStore метод getSumPlayedTime не суммирует время игроков

### ISSUE THREAD

**Issue by IraDol** [IraDol/team-project-origin#2]
# Описание
В классе GameStore при добавлении игроков в каталог store через метод addPlayTime время игроков не суммируется

# Локация дефекта
https://github.com/IraDol/team-project-origin/blob/c86d6da4536533e3f61cfc4dba14b86f8a31da15/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения

1. Открыть [класс GameStoreTest](https://github.com/IraDol/team-project-origin/blob/main/src/test/java/ru/netology/GameStoreTest.java#L8) в IDEA
2. Запустить тест shouldGetSumPlayerTime
3. Посмотреть результат теста в консоли

*Ожидаемый результат* - 12, сумма часов всех добавленных игроков в каталог store
*Фактический результат* - 0

# Скриншот
<img width="904" alt="image" src="https://user-images.githubusercontent.com/97681517/178452483-d3974c59-a24a-4676-9c21-606b649b5050.png">

# Окружение
* **Операционная система** macOS Big Sur
* **IDE** IntelliJ IDEA Community Edition 2022.1
* **Java** OpenJDK 11

**Comment by Natasssha** [comment]
Done
