### ISSUE TITLE
В классе GameStore метод addPlayTime не суммирует предыдущее время в игре с новым на нижней границе

### ISSUE THREAD

**Issue by IraDol** [IraDol/team-project-origin#3]
# Описание
В классе GameStore в методе addPlayTime часы, проведенные в игре, не суммируются с прошлым значением для этого игрока

# Локация дефекта
https://github.com/IraDol/team-project-origin/blob/f25b8e379867463f52acf77f6f67163d6ec9927a/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения

1. Открыть [класс GameStoreTest](https://github.com/IraDol/team-project-origin/blob/main/src/test/java/ru/netology/GameStoreTest.java#L8) в IDEA
2. Запустить тест shouldRegisteredTimeAndSumAllTimeOfPlayerLowBorder
3. Посмотреть результат теста в консоли

*Ожидаемый результат* - метод getMostPlayer вывел имя игрока "Petr"
*Фактический результат* - метод не увидел первое время игрока меньше часа и выдал null

# Скриншот
<img width="688" alt="image" src="https://user-images.githubusercontent.com/97681517/178480125-32fc3729-8bbf-457b-9522-f22ae3676963.png">

# Окружение
* **Операционная система** macOS Big Sur
* **IDE** IntelliJ IDEA Community Edition 2022.1
* **Java** OpenJDK 11

**Comment by Natasssha** [comment]
Done
