### ISSUE TITLE
В классе GameStore метод addPlayTime не видит игрока со временем 1 час и меньше

### ISSUE THREAD

**Issue by IraDol** [IraDol/team-project-origin#4]
# Описание
В классе GameStore метод addPlayTime не видит игрока с минимальным количеством часов в игре (1 час и меньше) и выдает null

# Локация дефекта
https://github.com/IraDol/team-project-origin/blob/f25b8e379867463f52acf77f6f67163d6ec9927a/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения
1. Открыть [класс GameStoreTest](https://github.com/IraDol/team-project-origin/blob/main/src/test/java/ru/netology/GameStoreTest.java#L8) в IDEA
2. Запустить тест shouldCheckUnderBorderOfTime2 со значением времени 1
3. Посмотреть результат теста в консоли

*Ожидаемый результат* - метод addPlayTime зафиксировал игрока и его время в игре, ОР - "Petr"
*Фактический результат* - метод addPlayTime не зафиксировал игрока и его время в игре, ФР - null

# Скриншот
<img width="715" alt="image" src="https://user-images.githubusercontent.com/97681517/178482342-4672232e-0ad4-4cfe-a082-f8d9bb53e11f.png">

# Окружение
* **Операционная система** macOS Big Sur
* **IDE** IntelliJ IDEA Community Edition 2022.1
* **Java** OpenJDK 11

**Comment by Natasssha** [comment]
Done
