### ISSUE TITLE
Player. Метод sumGenre не обновляет суммарное время игры по одному жанру.

### ISSUE THREAD

**Issue by Natasssha** [IraDol/team-project-origin#5]
# Описание
Метод player.SumGenre в классе Player не суммирует проигранное время игры одного жанра этим игроком.

# Локация дефекта

[Ссылка](https://github.com/IraDol/team-project-origin/blob/main/src/main/java/ru/netology/Player.java#:~:text=%7D-,/**%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D1%82%20%D0%B6%D0%B0%D0%BD%D1%80%20%D0%B8%D0%B3%D1%80%D1%8B%20(%D0%BE%D0%B4%D0%BD%D0%BE%20%D0%B8%D0%B7%20%D0%BF%D0%BE%D0%BB%D0%B5%D0%B9%20%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0%20%D0%B8%D0%B3%D1%80%D1%8B)%20%D0%B8,%7D,-/**%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D1%82%20%D0%B6%D0%B0%D0%BD%D1%80)

     /** Метод принимает жанр игры (одно из полей объекта игры) и
     суммирует время, проигранное во все игры этого жанра этим игроком */
    public int sumGenre(String genre) {
        int sum = 0;
        for (Game game : playedTime.keySet()) {
            if (game.getGenre().equals(genre)) {
                sum += playedTime.get(game);
            } else {
                sum = 0;
            }
        }
        return sum;
    }

# Шаги воспроизведения

1. Открыть [Тест  класса Player](https://github.com/IraDol/team-project-origin/blob/main/src/test/java/ru/netology/PlayerTest.java)
2. Запустить тест shouldSumGenreIfOneGame 
3. Посмотреть на результат теста в консоли

#### *Фактический результат:* Результат теста - Время игрока равно 0 часов, метод sumGenre вернул значение 0.

# Скриншот
![image](https://user-images.githubusercontent.com/102718243/178483020-d1654aaf-3507-4a3f-938c-abfc9b497662.png)

# Окружение
Операционная система: Windows 10 Домашняя
IDE: IntelliJ IDEA Community Edition 2022.1.1
Java: OpenJDK 11

**Comment by IraDol** [comment]
done
