### ISSUE TITLE
 Player. Метод play в классе Player не суммирует проигранное количество времени, сыгранное игроком, после установки игры.

### ISSUE THREAD

**Issue by Natasssha** [IraDol/team-project-origin#6]
# Описание
Метод play в классе Player не суммирует проигранное количество времени, сыгранное игроком, после установки игры.

# Локация дефекта
[Ссылка](https://github.com/IraDol/team-project-origin/blob/player/src/main/java/ru/netology/Player.java#:~:text=%7D-,/**%20%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%20%D0%B8%D0%B3%D1%80%D0%B0%D0%B5%D1%82%20%D0%B2%20%D0%B8%D0%B3%D1%80%D1%83%20game%20%D0%BD%D0%B0%20%D0%BF%D1%80%D0%BE%D1%82%D1%8F%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8%20hours%20%D1%87%D0%B0%D1%81%D0%BE%D0%B2,%7D,-/**%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D1%82%20%D0%B6%D0%B0%D0%BD%D1%80)

 /** игрок играет в игру game на протяжении hours часов
    об этом нужно сообщить объекту-каталогу игр, откуда была установлена игра
    также надо обновить значения в мапе игрока, добавив проигранное количество часов
    возвращает суммарное количество часов, проигранное в эту игру.
    если игра не была установлена, то надо выкидывать RuntimeException */

    public int play(Game game, int hours) {
        game.getStore().addPlayTime(name, hours);
        if (playedTime.containsKey(game)) {
            playedTime.put(game, playedTime.get(game));
        } else {
            playedTime.put(game, hours);
        }
        return playedTime.get(game);
    }

# Шаги воспроизведения
1. Открыть [Тест класса Player](https://github.com/IraDol/team-project-origin/blob/player/src/test/java/ru/netology/PlayerTest.java#:~:text=%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5%20%D0%B2%D0%B0%D1%88%D0%B8%20%D1%82%D0%B5%D1%81%D1%82%D1%8B-,%40Test,%7D,-%40Test) в IDEA.
2. Запустить тест shouldPlay
3. Посмотреть на результат теста в консоли

#### *Фактический результат:*  Результат теста - Время игрока равно 0 часов, метод sumGenre вернул значение 0.
# Скриншот
![image](https://user-images.githubusercontent.com/102718243/178712062-bf70b2ba-9f25-4095-afcd-a78eb972883f.png)

# Окружение
Операционная система: Windows 10 Домашняя
IDE: IntelliJ IDEA Community Edition 2022.1.1
Java: OpenJDK 11

**Comment by IraDol** [comment]
done
