### ISSUE TITLE
Player. Метод mostPlayerByGenre(String genre) в классе Player не возвращает название игры жанра.

### ISSUE THREAD

**Issue by Natasssha** [IraDol/team-project-origin#8]
# Описание
Метод mostPlayerByGenre(String genre) в классе Player не возвращает название игры жанра  в которую играли больше всего, а возвращает значение null.

# Локация дефекта
[Ссылка](https://github.com/IraDol/team-project-origin/blob/player/src/main/java/ru/netology/Player.java#:~:text=/**%20%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%B5%D1%82%20%D0%B6%D0%B0%D0%BD%D1%80%20%D0%B8,%7D)

 /** Метод принимает жанр и возвращает игру этого жанра, в которую играли больше всего
     Если в игры этого жанра не играли, возвращается null */
    public Game mostPlayerByGenre(String genre) {
        return null;
    }

# Шаги воспроизведения
1. Открыть [Тест класса Player](https://github.com/IraDol/team-project-origin/blob/player/src/test/java/ru/netology/PlayerTest.java#:~:text=%7D-,%40%D0%A2%D0%B5%D1%81%D1%82,%7D,-%40%D0%A2%D0%B5%D1%81%D1%82) в IDEA.
2. Запустить тест shouldMostPlayerByGenre
3. Посмотреть на результат теста в консоли

#### *Фактический результат:* Результат теста - Метод mostPlayerByGenre("Аркады") вернул значение Null.

# Скриншот
![image](https://user-images.githubusercontent.com/102718243/178718475-3127d058-94f1-405a-ad51-36671decbdab.png)

Окружение
Операционная система: Windows 10 Домашняя
IDE: IntelliJ IDEA Community Edition 2022.1.1
Java: OpenJDK 11

**Comment by IraDol** [comment]
done
